version: '2'

services:

  istex-ark-ws:
    container_name: istex-ark-ws
    image: node:6.9.1
    working_dir: /app
    volumes:
      - .:/app
    tty: true
    stdin_open: true  # to be able to use CTRL+C to stop the debug
    environment:
      NODE_ENV: "development"
      DEBUG: ${DEBUG}
    ports:
      - 45446:3000
      - 3000:3000
    links:
      - istex-ark-redis
    command: npm run debug


  istex-ark-redis:
    container_name: istex-ark-redis
    image: redis:3.2.8
    volumes:
      - ./redis-data:/data
    command: redis-server --appendonly yes # cf http://download.redis.io/redis-stable/redis.conf
