version: '2'

services:

  istex-ark:
    container_name: istex-ark
    image: node:6.9.1
    working_dir: /app
    volumes:
      - .:/app
    tty: true
    stdin_open: true  # to be able to use CTRL+C to stop the debug
    environment:
      NODE_ENV: "development"
      DEBUG: ${DEBUG}
    ports:
      - 45446:3000
      - 3000:3000
    depends_on:
      - istex-ark-db
    command: npm run debug

  istex-ark-db:
    container_name: istex-ark-db
    image: mongo:3.3.15
    command: --smallfiles
    volumes:
      - ./data:/data/db