version: '2'

services:

  istex-ark:
    container_name: istex-ark
    image: istex/istex-ark:1.0.0
    ports:
      - 45446:3000

  istex-ark-db:
    container_name: istex-ark-db
    image: mongo:3.3.15
    command: --smallfiles
    restart: unless-stopped
    volumes:
      - ./data:/data/db