version: '2'

services:

  istex-ark-ws:
    container_name: istex-ark-ws
    image: istex/istex-ark:2.4.0
    links:
      - istex-ark-redis
    environment:
      - NODE_ENV
      - DEBUG
    ports:
      - 45446:3000

  istex-ark-redis:
    container_name: istex-ark-redis
    image: redis:3.2.8
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf # cf http://download.redis.io/redis-stable/redis.conf
