version: '2'

services:

  lmdb-install:
    container_name: lmdb-install
    build: .
    image: istex/lmdb-install
    volumes:
      - .:/app
    working_dir: /app
    command: [ "npm", "install" ]
    tty: true         # to have nice debug(...) outputs
    stdin_open: true  # to be able to use CTRL+C to stop the debug

  lmdb-reader:
    container_name: lmdb-reader
    build: .
    image: istex/lmdb-reader
    volumes:
      - .:/app
    working_dir: /app
    command: [ "node", "reader.js" ]
    #tty: true         # to have nice debug(...) outputs
    stdin_open: true  # to be able to use CTRL+C to stop the debug

  lmdb-writer:
    container_name: lmdb-writer
    build: .
    image: istex/lmdb-writer
    volumes:
      - .:/app
    working_dir: /app
    command: [ "node", "writer.js" ]
    #tty: true         # to have nice debug(...) outputs
    stdin_open: true  # to be able to use CTRL+C to stop the debug
